apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: rails-kube-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: rails-kube-app
      tier: database
  template:
    metadata:
      name: postgres
      labels:
        app: rails-kube-app
        tier: database
    spec:
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-pvc
      containers:
      - name: postgres
        image: postgres:13-alpine
        env:
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_PASSWORD
          value: root
        - name: POSTGRES_DB
          value: "kubernetes-rails-example_production"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-pv